# Generated by Django 2.1.15 on 2020-08-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdetails',
            old_name='card_number',
            new_name='merchant_account',
        ),
    ]
