# Generated by Django 2.1.15 on 2020-08-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200810_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='user',
            name='cart_list',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
